version: '3.6'

services:
  web:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    build: .
    restart: always
    environment:
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
    networks:
      - gitlab

networks:
  gitlab:
    external: true
