version: '3.6'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab
    restart: always
    environment:
      LETSENCRYPT_HOST: gitlab.mydomain.com,registry-gitlab.mydomain.com
      VIRTUAL_HOST: gitlab.mydomain.com,registry-gitlab.mydomain.com
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      GITLAB_HOME: /srv/gitlab
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.mydomain.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['dependency_proxy_enabled'] = true
        registry_external_url 'https://registry-gitlab.mydomain.com'
        gitlab_rails['registry_host'] = 'registry-gitlab.mydomain.com'
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.mydomain.com/fullchain.pem"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.mydomain.com/key.pem"
        registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.mydomain.com/fullchain.pem"
        registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.mydomain.com/key.pem"
    ports:
      - '2224:22'
    volumes:
      - certs:/etc/gitlab/ssl/:ro
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
      - /srv/gitlab/registry:/srv/gitlab/registry
      - /var/run/docker.sock:/var/run/docker.sock:ro
    shm_size: '256m'
    networks:
      - gitlab

volumes:
  certs:

networks:
  gitlab:
    external: true
