version: '3.6'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab
    restart: always
    environment:
      LETSENCRYPT_HOST: gitlab.mydomain.com
      VIRTUAL_HOST: gitlab.mydomain.com
      VIRTUAL_PORT: 8929
      GITLAB_HOME: /srv/gitlab
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.mydomain.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929'
      - '2224:22'
    volumes:
      - ${GITLAB_HOME}/config:/etc/gitlab
      - ${GITLAB_HOME}/logs:/var/log/gitlab
      - ${GITLAB_HOME}/data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - gitlab

networks:
  gitlab:
    external: true
